### PR TITLE
Turn zookeeper nodes to EPHEMERAL ones

### PR DESCRIPTION
**Pull request by amarouni**
This is in response to #30.
This has been tested on Zookeeper 3.4.9

### CODE REVIEW

**Comment by markusjura** [comment]
@amarouni Good catch, thanks for the change. I've approved it. However, I do not have merge rights because I am not part of the `typesafehub` organization anymore.

@fsat @longshorej Can one of you merge this PR and create a new release?

**Review by markusjura — APPROVED** [review]

**Comment by markusjura** [comment]
@amarouni Can you remove the debug logging. They would create quite a lot of debug message in case the log level is enabled.

**Comment by longshorej** [comment]
Hey Markus, I’ll look at merging and releasing tomorrow.

**Comment by amarouni** [comment]
@markusjura @longshorej :+1: 
I removed the debug logging. Looking forward for the new release.

**Review by longshorej — APPROVED** [review]

**Comment by fkoehler** [comment]
Any chance we can have a release for the latest fixes including this one? Thanks!

**Comment by longshorej** [comment]
Apologies for the delay, something strange with the build and I haven't had time to figure it out. I put a workaround in via PR #36 so that I could get a release out:

Thus, `0.4.1` is released, should be synced to Maven Central shortly.

/cc @fkoehler @markusjura @amarouni

**Comment by fkoehler** [comment]
Thank you very much for the quick work around.

Jason Longshore <notifications@github.com> schrieb am Sa., 2. Dez. 2017,
15:06:

**Pull request merged**
